all: clean tst_d

tst_d: tst_d.o model.o events.o
	cc68x -g tst_d.o model.o events.o -o tst_d

tst_d.o: tst_d.c model.h events.h
	cc68x -g -c tst_d.c 

model.o: model.c model.h
	cc68x -g -c model.c

events.o: events.c events.h
	cc68x -g -c events.c

clean:
	$(RM) *.o *.tos
