#ifndef TYPES_H
#define TYPES_H

#define ASTEROID_HEIGHT 8
#define SPACESHIP_HEIGHT 32
#define NUMBER_HEIGHT 32
#define HEART_HEIGHT 16
#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 400
#define FIRST_DIGIT 550
#define SECOND_DIGIT 580
#define THIRD_DIGIT 610
#define SCORE_ROW 10
#define w 119
#define s 115
#define ESC 27
#define SPACE 32

typedef unsigned char UINT8;
typedef unsigned int  UINT16;
typedef unsigned long UINT32;

#endif
