all: clean game

game: game.o render.o raster.o model.o events.o music.o psg.o effects.o rast_asm.o
	cc68x -g game.o render.o raster.o model.o events.o music.o psg.o effects.o rast_asm.o -o game

game.o: game.c
	cc68x -g -c game.c

tst_mus.o: tst_mus.c
	cc68x -g -c tst_mus.c

raster.o: raster.c raster.h 
	cc68x -g -c raster.c

model.o: model.c model.h
	cc68x -g -c model.c

events.o: events.c events.h
	cc68x -g -c events.c

render.o: render.c render.h
	cc68x -g -c render.c

music.o: music.c music.h
	cc68x -g -c music.c

psg.o: psg.c psg.h
	cc68x -g -c psg.c

effects.o: effects.c effects.h
	cc68x -g -c effects.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s

clean:
	$(RM) *.o *.tos
