all: clean pregame

pregame: pregame.o render.o raster.o model.o events.o
	cc68x -g pregame.o render.o raster.o model.o events.o -o pregame

pregame.o: pregame.c
	cc68x -g -c pregame.c

raster.o: raster.c raster.h 
	cc68x -g -c raster.c

model.o: model.c model.h
	cc68x -g -c model.c

events.o: events.c events.h
	cc68x -g -c events.c

render.o: render.c render.h
	cc68x -g -c render.c

clean:
	$(RM) *.o *.tos
