tst_rast: tst_rast.o raster.o model.o events.o
	cc68x -g tst_rast.o raster.o model.o events.o -o tst_rast 

tst_rast.o: tst_rast.c raster.h bitmap.h model.h events.h
	cc68x -g -c tst_rast.c 

raster.o: raster.c raster.h 
	cc68x -g -c raster.c

model.o: model.c model.h
	cc68x -g -c model.c

events.o: events.c events.h
	cc68x -g -c events.c

clean:
	$(RM) *.o *.tos
