all: clean tst_rend

tst_rend: tst_rend.o render.o raster.o model.o
	cc68x -g tst_rend.o render.o raster.o model.o -o tst_rend

tst_rend.o: tst_rend.c raster.h render.h model.h
	cc68x -g -c tst_rend.c 

raster.o: raster.c raster.h 
	cc68x -g -c raster.c

model.o: model.c model.h
	cc68x -g -c model.c

events.o: events.c events.h
	cc68x -g -c events.c

render.o: render.c render.h
	cc68x -g -c render.c

clean:
	$(RM) *.o *.tos
