all: clean game

game: game.o render.o raster.o model.o events.o
	cc68x -g game.o render.o raster.o model.o events.o -o game

game.o: game.c
	cc68x -g -c game.c

tst_mus.o: tst_mus.c
	cc68x -g -c tst_mus.c

raster.o: raster.c raster.h 
	cc68x -g -c raster.c

model.o: model.c model.h
	cc68x -g -c model.c

events.o: events.c events.h
	cc68x -g -c events.c

render.o: render.c render.h
	cc68x -g -c render.c

clean:
	$(RM) *.o *.tos
