all: clean tst_mus

tst_mus: tst_mus.o music.o psg.o
	cc68x -g tst_mus.o music.o psg.o -o tst_mus

tst_mus.o: tst_mus.c
	cc68x -g -c tst_mus.c

music.o: music.c music.h
	cc68x -g -c music.c

psg.o: psg.c psg.h
	cc68x -g -c psg.c

clean:
	$(RM) *.o *.tos
